/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Dimension;
import java.io.File;
import java.sql.Connection;
import java.sql.SQLException;

import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Rectangle;

import BackupAndRestore.PostgresBackup;
import Daos.ConfigDAO;
import Models.ConfigModel;

/**
 *
 * @author vitor
 */
public class frameBackup extends javax.swing.JInternalFrame {

	/**
	 * Creates new form frameBackup
	 */
	public frameBackup(Connection conn) {
		this.conn = conn;
		initComponents();
		configDao = new ConfigDAO(conn);

		try {
			config = configDao.getConfig(0);
			fixFields();
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */

	private String dirSave;
	private String dirDump;
	private String nome;
	private String user;
	private String senha;
	private String nomeArquivo = "";
	private String ip;
	private String porta;
	private ConfigDAO configDao;
	private ConfigModel config;
	private Connection conn;

	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		txtDirSave = new javax.swing.JTextField();
		jLabel2 = new javax.swing.JLabel();
		txtDirDump = new javax.swing.JTextField();
		btnDirDump = new javax.swing.JButton();
		jLabel3 = new javax.swing.JLabel();
		txtNome = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();
		txtSenha = new javax.swing.JTextField();
		btnSalvar = new javax.swing.JButton();
		btnCancelar = new javax.swing.JButton();
		txtUsuario = new javax.swing.JTextField();
		jLabel5 = new javax.swing.JLabel();
		btnDirSave = new javax.swing.JButton();
		JLabel jLabel6 = new javax.swing.JLabel();
		JLabel jLabel7 = new javax.swing.JLabel();
		txtPorta = new javax.swing.JTextField();
		txtIp = new javax.swing.JTextField();

		setClosable(true);
		setIconifiable(true);
		setTitle("Backup");

		jLabel1.setText("Diretório de Save");

		txtDirSave.setText("C:\\Users\\" + System.getProperty("user.name") + "\\Documents");
		txtDirSave.setToolTipText("Diretório de registro");
		txtDirSave.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				txtDirSaveActionPerformed(evt);
			}
		});

		jLabel2.setText("Diretório Pg_Dump");

		txtDirDump.setToolTipText("Diretório de registro");
		txtDirDump.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				txtDirDumpActionPerformed(evt);
			}
		});

		btnDirDump.setText("...");
		btnDirDump.setToolTipText("Buscar");
		btnDirDump.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnDirDumpActionPerformed(evt);
			}
		});

		jLabel3.setText("Nome do Banco");

		txtNome.setToolTipText("Nome do Banco");
		txtNome.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				txtNomeActionPerformed(evt);
			}
		});

		jLabel4.setText("Senha do Banco");

		txtSenha.setToolTipText("Senha do Banco");
		txtSenha.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				txtSenhaActionPerformed(evt);
			}
		});

		btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/disquetex32.png"))); // NOI18N
		btnSalvar.setToolTipText("Salvar");
		btnSalvar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnSalvarActionPerformed(evt);
			}
		});

		btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/proibido.png"))); // NOI18N
		btnCancelar.setToolTipText("Cancelar");
		btnCancelar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnCancelarActionPerformed(evt);
			}
		});

		txtUsuario.setToolTipText("Senha do Banco");
		txtUsuario.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				txtUsuarioActionPerformed(evt);
			}
		});

		jLabel5.setText("Usuário");

		btnDirSave.setText("...");
		btnDirSave.setToolTipText("Buscar");
		btnDirSave.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnDirSaveActionPerformed(evt);
			}
		});

		jLabel6.setText("IP");

		jLabel7.setText("Porta");

		txtPorta.setToolTipText("Porta do banco");
		txtPorta.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				txtPortaActionPerformed(evt);
			}
		});

		txtIp.setToolTipText("Senha do Banco");
		txtIp.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				txtIpActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup().addContainerGap()
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup().addComponent(btnSalvar).addGap(18, 18, 18)
								.addComponent(btnCancelar))
						.addGroup(layout.createSequentialGroup()
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
										.addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
										.addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
										.addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
										.addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(layout.createSequentialGroup()
												.addComponent(txtDirDump, javax.swing.GroupLayout.PREFERRED_SIZE, 311,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(btnDirDump, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGroup(layout.createSequentialGroup()
												.addComponent(txtDirSave, javax.swing.GroupLayout.PREFERRED_SIZE, 311,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(btnDirSave, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGroup(layout.createSequentialGroup().addGroup(layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
												.addGroup(layout.createSequentialGroup()
														.addComponent(txtUsuario,
																javax.swing.GroupLayout.PREFERRED_SIZE, 100,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
														.addComponent(jLabel7))
												.addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout
														.createSequentialGroup()
														.addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE,
																100, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGap(18, 18, 18).addComponent(jLabel4)))
												.addGap(18, 18, 18)
												.addGroup(layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE,
																100, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(txtPorta, javax.swing.GroupLayout.PREFERRED_SIZE,
																100, javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addComponent(txtIp, javax.swing.GroupLayout.PREFERRED_SIZE, 100,
												javax.swing.GroupLayout.PREFERRED_SIZE))))
				.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup().addGap(8, 8, 8)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(btnSalvar)
						.addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 43,
								javax.swing.GroupLayout.PREFERRED_SIZE))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel1).addComponent(txtDirSave, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addComponent(btnDirSave))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(btnDirDump)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel2).addComponent(txtDirDump, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel3)
						.addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(jLabel4).addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel5)
						.addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(jLabel7).addComponent(txtPorta, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel6)
						.addComponent(txtIp, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addContainerGap(38, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>

	private void txtDirSaveActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void txtDirDumpActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void txtSenhaActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void txtPortaActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void txtIpActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void btnDirDumpActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		JFileChooser chooser = new JFileChooser(
				new File("C:\\Users\\" + System.getProperty("user.name") + "\\Documents"));
		chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
		chooser.setDialogTitle("Selecione o diretorio do pg_dump");
		String path;
		if (chooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
			if (!chooser.getSelectedFile().getName().equals("pg_dump.exe")) {
				JOptionPane.showMessageDialog(null, "Arquivo inválido", "Inválido!", JOptionPane.ERROR_MESSAGE,
						new javax.swing.ImageIcon(getClass().getResource("/Imagens/sinal-de-avisox32.png")));
			} else {
				dirDump = chooser.getSelectedFile().getPath();
				txtDirDump.setText(chooser.getSelectedFile().getPath());
			}
		}
	}

	private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		if (txtDirDump.getText().isEmpty() || txtDirSave.getText().isEmpty() || txtNome.getText().isEmpty()
				|| txtSenha.getText().isEmpty() || txtUsuario.getText().isEmpty() || txtDirDump.getText().equals(" ") || txtDirSave.getText().equals(" ") || txtNome.getText().equals(" ")
				|| txtSenha.getText().equals(" ") || txtUsuario.getText().equals(" ")) {
			JOptionPane.showMessageDialog(null, "Preencha todos os campos!", "falha!", JOptionPane.ERROR_MESSAGE,
					new javax.swing.ImageIcon(getClass().getResource("/Imagens/sinal-de-avisox32.png")));
		} else {
			dirSave = txtDirSave.getText().toString();
			if (nomeArquivo == "") {
				String text = (String) JOptionPane.showInputDialog(null, "Informe o nome do documento:", "documento",
						JOptionPane.DEFAULT_OPTION,
						new javax.swing.ImageIcon(getClass().getResource("/Imagens/disquetex64.png")), null, "");
				dirSave = dirSave + "\\" + text;
			}
			String formato = dirSave.substring(dirSave.length()-4);
			if(!formato.equals(".sql")) {
				dirSave = dirSave + ".sql";	
			}	
			PostgresBackup pkb = new PostgresBackup(dirSave.replace(" ", ""), txtDirDump.getText().toString().replace(" ", ""),
					txtNome.getText().toString().replace(" ", ""), txtSenha.getText().toString().replace(" ", ""), txtUsuario.getText().toString().replace(" ", ""),
					txtIp.getText().toString().replace(" ", ""), txtPorta.getText().toString().replace(" ", ""), 0 );

		}
	}

	private void btnDirSaveActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		JFileChooser chooser = new JFileChooser(
				new File("C:\\Users\\" + System.getProperty("user.name") + "\\Documents"));
		chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
		chooser.setDialogTitle("Selecione o destino");
		String path;
		if (chooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
			String text = (String) JOptionPane.showInputDialog(null, "Informe o nome do documento:", "documento",
					JOptionPane.DEFAULT_OPTION,
					new javax.swing.ImageIcon(getClass().getResource("/Imagens/disquetex64.png")), null, "");
			nomeArquivo = text;

			String formato = text.substring(text.length()-4);
			if(!formato.equals(".sql")) {
			text = text + ".sql";	
			}	
			dirSave = chooser.getSelectedFile() + ("\\" + text);
			txtDirSave.setText(chooser.getSelectedFile() + ("\\" + text + ".sql"));
		}
	}

	public void fixFields() {
		txtDirDump.setText(config.getPgDump());
		txtNome.setText(config.getNomeBanco());
		txtSenha.setText(config.getSenhaBanco());
		txtUsuario.setText(config.getUserBanco());
		txtPorta.setText(config.getPortaBanco());
		txtIp.setText(config.getIpBanco());
	}

	public void setPosicao() {
		Dimension d = this.getDesktopPane().getSize();
		this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
	}

	// Variables declaration - do not modify
	private javax.swing.JButton btnCancelar;
	private javax.swing.JButton btnDirSave;
	private javax.swing.JButton btnSalvar;
	private javax.swing.JButton btnDirDump;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JTextField txtDirDump;
	private javax.swing.JTextField txtDirSave;
	private javax.swing.JTextField txtNome;
	private javax.swing.JTextField txtSenha;
	private javax.swing.JTextField txtUsuario;
	private javax.swing.JTextField txtPorta;
	private javax.swing.JTextField txtIp;
	// End of variables declaration
}