/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Dimension;
import java.sql.Connection;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;

import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.MaskFormatter;

import Daos.produtoDAO;
import Models.ProdutoModel;

/**
 *
 * @author vitor
 */
public class frameProdutos extends javax.swing.JInternalFrame {

    /**
	 * Creates new form frameProdutos		
	 */
	private Connection conn;
	private produtoDAO produtoDao;
	private DefaultTableModel model;
	private ProdutoModel produto, produtoChange;
	private boolean isInserting = true;

	public frameProdutos(Connection conn) {
		this.conn = conn;
		produtoDao = new produtoDAO(conn);
		initComponents();
		btnGravar.setEnabled(false);
		try {
			fixTable();
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		txtNome = new javax.swing.JTextField();
		ComboboxProdutos = new javax.swing.JComboBox<>();
		btnSalvar = new javax.swing.JButton();
		btnBuscar = new javax.swing.JButton();
		btnDeletar = new javax.swing.JButton();
		btnCancelar = new javax.swing.JButton();
		jLabel2 = new javax.swing.JLabel();
		txtBarCode = new javax.swing.JTextField();
		btnGravar = new javax.swing.JButton();
		jLabel3 = new javax.swing.JLabel();
		txtValor = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();
		txtQuantidade = new javax.swing.JTextField();
		jLabel5 = new javax.swing.JLabel();
		try {
			MaskFormatter mask = new MaskFormatter("##/##/####");
			mask.setPlaceholderCharacter('_');	
		txtValidade = new JFormattedTextField(mask);
		} catch (Exception e) {
			// TODO: handle exception
		}
		jScrollPane2 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();

		setClosable(true);
		setIconifiable(true);
		setTitle("Cadastro de Produtos");

		jLabel1.setText("Nome do produto");

		txtNome.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				txtNomeActionPerformed(evt);
			}
		});

		ComboboxProdutos.setModel(new javax.swing.DefaultComboBoxModel<>(
				new String[] { "Selecione", "Bebida", "Alimento", "Item", "Outros" }));

		btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/disquetex32.png"))); // NOI18N
		btnSalvar.setToolTipText("Salvar");
		btnSalvar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				try {
					if (txtBarCode.getText().isEmpty() || txtNome.getText().isEmpty()
							|| txtQuantidade.getText().isEmpty() || txtValidade.getText().isEmpty()
							|| txtValor.getText().isEmpty()) {
						JOptionPane.showMessageDialog(null, "Preencha todos os campos!", "campos!",
								JOptionPane.ERROR_MESSAGE,
								new javax.swing.ImageIcon(getClass().getResource("/Imagens/sinal-de-avisox24.png")));
					} else if (ComboboxProdutos.getSelectedIndex() == 0) {
						JOptionPane.showMessageDialog(null, "Selecione uma categoria", "categoria!",
								JOptionPane.ERROR_MESSAGE,
								new javax.swing.ImageIcon(getClass().getResource("/Imagens/sinal-de-avisox24.png")));

					} else {
						btnSalvarActionPerformed(evt);
						fixTable();
						System.out.println("foi tentar salvar!");
					}

				} catch (ParseException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		});

		btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/procurar.png"))); // NOI18N
		btnBuscar.setToolTipText("Procurar");
		btnBuscar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnBuscarActionPerformed(evt);
			}
		});

		btnDeletar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/lixeira-de-reciclagem.png"))); // NOI18N
		btnDeletar.setToolTipText("Deletar");
		btnDeletar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnDeletarActionPerformed(evt);
			}
		});

		btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/proibido.png"))); // NOI18N
		btnCancelar.setToolTipText("Cancelar");
		btnCancelar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnCancelarActionPerformed(evt);
			}
		});

		jLabel2.setText("Codigo de Barras");

		txtBarCode.setToolTipText("");
		txtBarCode.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				txtBarCodeActionPerformed(evt);
			}
		});

		btnGravar.setText("Gravar");
		btnGravar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnGravarActionPerformed(evt);
			}
		});

		jLabel3.setText("Valor");

		txtValor.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				txtValorActionPerformed(evt);
			}
		});

		jLabel4.setText("Quantidade");

		txtQuantidade.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				txtQuantidadeActionPerformed(evt);
			}
		});

		jLabel5.setText("Data de Validade");

		jTable1.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { null, null, null, null, null }, { null, null, null, null, null },
						{ null, null, null, null, null }, { null, null, null, null, null } },
				new String[] { "Codigo", "Nome", "Valor", "Quantidade", "Data de Validade" }));
		jScrollPane2.setViewportView(jTable1);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										layout.createSequentialGroup().addComponent(jLabel1)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
												.addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 153,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(12, 12, 12).addComponent(ComboboxProdutos, 0,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
								.addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE)
								.addGroup(layout.createSequentialGroup().addGroup(layout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(layout
												.createSequentialGroup().addGroup(
														layout.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
																.addComponent(jLabel2).addComponent(jLabel3)
																.addComponent(jLabel5))
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
												.addGroup(layout.createParallelGroup(
														javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(layout.createSequentialGroup().addComponent(
																txtBarCode, javax.swing.GroupLayout.PREFERRED_SIZE, 153,
																javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																.addComponent(btnGravar))
														.addGroup(layout.createSequentialGroup().addComponent(
																txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 72,
																javax.swing.GroupLayout.PREFERRED_SIZE)
																.addGap(26, 26, 26).addComponent(jLabel4)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																.addComponent(txtQuantidade,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 72,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
														.addComponent(txtValidade,
																javax.swing.GroupLayout.PREFERRED_SIZE, 109,
																javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addGroup(
												layout.createSequentialGroup()
														.addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE,
																55, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGap(18, 18, 18)
														.addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE,
																55, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGap(18, 18, 18)
														.addComponent(btnDeletar,
																javax.swing.GroupLayout.PREFERRED_SIZE, 55,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGap(18, 18, 18).addComponent(btnCancelar,
																javax.swing.GroupLayout.PREFERRED_SIZE, 55,
																javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addGap(0, 247, Short.MAX_VALUE)))
						.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
										.addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 42,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 42,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(btnDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 42,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 43,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel1)
								.addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(ComboboxProdutos, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel2)
								.addComponent(txtBarCode, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(btnGravar))
						.addGap(18, 18, 18)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel4)
								.addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel5).addComponent(txtValidade, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18).addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 268,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap()));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtNomeActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_txtNomeActionPerformed

	private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) throws ParseException {// GEN-FIRST:event_btnSalvarActionPerformed
		// TODO add your handling code here:

		try {

			getFields();
			if (isInserting) {
				if(produtoDao.getOneProdutoBar(produtoChange.getBarCode()) != null) {
					JOptionPane.showMessageDialog(null, "Produto ja cadastrado!", "falha!",
							JOptionPane.ERROR_MESSAGE,
							new javax.swing.ImageIcon(getClass().getResource("/Imagens/sinal-de-avisox24.png")));
				}
				else {
				produtoDao.createProduto(produtoChange);
				JOptionPane.showMessageDialog(null, "Produto cadastrado com sucesso!!", "Sucesso!",
						JOptionPane.INFORMATION_MESSAGE,
						new javax.swing.ImageIcon(getClass().getResource("/Imagens/verificado.png")));
				}
			} else {
				produtoDao.updateProduto(produtoChange);
			}
		} catch (SQLException e) {
		}

	}// GEN-LAST:event_btnSalvarActionPerformed

	private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnBuscarActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_btnBuscarActionPerformed

	private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnDeletarActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_btnDeletarActionPerformed

	private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnCancelarActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_btnCancelarActionPerformed

	private void txtBarCodeActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtBarCodeActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_txtBarCodeActionPerformed

	private void btnGravarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnGravarActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_btnGravarActionPerformed

	private void txtValorActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtValorActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_txtValorActionPerformed

	private void txtQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtQuantidadeActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_txtQuantidadeActionPerformed

	public void setPosicao() {
		Dimension d = this.getDesktopPane().getSize();
		this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
	}

	private void fixTable() throws SQLException {
		this.model = (DefaultTableModel) jTable1.getModel();
		model.setRowCount(0);
		ArrayList<ProdutoModel> list = new ArrayList<ProdutoModel>();
		list = produtoDao.getAllProducts();
		for (ProdutoModel produto : list) {
			InsertRow(produto);
		}
	}

	private void InsertRow(ProdutoModel produto) {
		model.addRow(new String[] { Integer.toString(produto.getBarCode()), produto.getNome(),
				Double.toString(produto.getPreco()), Integer.toString(produto.getQuantidade()), produto.getValDate() });

	}

	private void getFields() throws ParseException {
		if (produtoChange == null) {
			produtoChange = new ProdutoModel();
		}
		produtoChange.setNome(txtNome.getText());
		produtoChange.setBarCode(Integer.parseInt(txtBarCode.getText()));
		produtoChange.setCategoria(ComboboxProdutos.getSelectedItem().toString());
		produtoChange.setPreco(Double.valueOf(txtValor.getText()));
		produtoChange.setQuantidade(Integer.parseInt(txtQuantidade.getText()));
		SimpleDateFormat fmt = new SimpleDateFormat("dd/MM/yyyy");
		produtoChange.setValDate(fmt.parse(txtValidade.getText()));

	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JComboBox<String> ComboboxProdutos;
	private javax.swing.JButton btnBuscar;
	private javax.swing.JButton btnCancelar;
	private javax.swing.JButton btnDeletar;
	private javax.swing.JButton btnGravar;
	private javax.swing.JButton btnSalvar;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JTable jTable1;
	private javax.swing.JTextField txtBarCode;
	private javax.swing.JTextField txtNome;
	private javax.swing.JTextField txtQuantidade;
	private javax.swing.JTextField txtValidade;
	private javax.swing.JTextField txtValor;
	// End of variables declaration//GEN-END:variables
}
