/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.net.URL;
import java.sql.Connection;

import javax.swing.ImageIcon;
import javax.swing.JDesktopPane;
import javax.swing.JFrame;

/**
 *
 * @author vitor
 */
public class ViewMenu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
	private Connection conn;
    public ViewMenu(Connection conn) {
    	this.conn = conn;
        initComponents();
        //setExtendedState(JFrame.MAXIMIZED_BOTH);
        

        


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane2 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mMenu = new javax.swing.JMenu();
        mMenuProdutos = new javax.swing.JMenuItem();
        mMenuUsuario = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mMenuSair = new javax.swing.JMenuItem();
        mVendas = new javax.swing.JMenu();
        mVendasVendas = new javax.swing.JMenuItem();
        mVendasRelatorioVendas = new javax.swing.JMenuItem();
        mAjuda = new javax.swing.JMenu();
        mAjudaAjuda = new javax.swing.JMenuItem();
        mAjudaSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1050, 700));
        setResizable(false);
        setSize(new java.awt.Dimension(1500, 70));
        getContentPane().setLayout(null);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cerveja.png"))); // NOI18N
        jLabel1.setFocusable(false);
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setOpaque(true);
        jLabel1.setVerifyInputWhenFocusTarget(false);
        jDesktopPane2.add(jLabel1);
        jLabel1.setBounds(0, 0, 1050, 700);

        getContentPane().add(jDesktopPane2);
        jDesktopPane2.setBounds(0, 0, 1050, 700);


        mMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/MenuIcon.png"))); // NOI18N
        mMenu.setText("Menu");

        mMenuProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/produtos.png"))); // NOI18N
        mMenuProdutos.setText("Produtos");
        mMenuProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mMenuProdutosActionPerformed(evt);
            }
        });
        mMenu.add(mMenuProdutos);

        mMenuUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/assaltante.png"))); // NOI18N
        mMenuUsuario.setText("Usuário");
        mMenuUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mMenuUsuarioActionPerformed(evt);
            }
        });
        mMenu.add(mMenuUsuario);
        mMenu.add(jSeparator1);

        mMenuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/sair.png"))); // NOI18N
        mMenuSair.setText("Sair");
        mMenu.add(mMenuSair);

        jMenuBar1.add(mMenu);

        mVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/vendaIcon.png"))); // NOI18N
        mVendas.setText("Vendas");

        mVendasVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/comercio.png"))); // NOI18N
        mVendasVendas.setText("Vendas");
        mVendasVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mVendasVendasActionPerformed(evt);
            }
        });
        mVendas.add(mVendasVendas);

        mVendasRelatorioVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/relatorio-de-venda.png"))); // NOI18N
        mVendasRelatorioVendas.setText("Relatório de Vendas");
        mVendas.add(mVendasRelatorioVendas);

        jMenuBar1.add(mVendas);

        mAjuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/computador-desktop.png"))); // NOI18N
        mAjuda.setText("Ajuda");

        mAjudaAjuda.setText("Ajuda");
        mAjuda.add(mAjudaAjuda);

        mAjudaSobre.setText("Sobre");
        mAjuda.add(mAjudaSobre);

        jMenuBar1.add(mAjuda);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mMenuProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mMenuProdutosActionPerformed
        // TODO add your handling code here:
        frameProdutos fprodutos = new frameProdutos(conn);
        jDesktopPane2.add(fprodutos);
        fprodutos.setPosicao();
        fprodutos.show();
    }//GEN-LAST:event_mMenuProdutosActionPerformed

    private void mMenuUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mMenuUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mMenuUsuarioActionPerformed

    private void mVendasVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mVendasVendasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mVendasVendasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new ViewMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenu mAjuda;
    private javax.swing.JMenuItem mAjudaAjuda;
    private javax.swing.JMenuItem mAjudaSobre;
    private javax.swing.JMenu mMenu;
    private javax.swing.JMenuItem mMenuProdutos;
    private javax.swing.JMenuItem mMenuSair;
    private javax.swing.JMenuItem mMenuUsuario;
    private javax.swing.JMenu mVendas;
    private javax.swing.JMenuItem mVendasRelatorioVendas;
    private javax.swing.JMenuItem mVendasVendas;
    // End of variables declaration//GEN-END:variables
}
