/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.BorderLayout;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.Frame;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import java.net.URL;
import java.sql.Connection;

import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JDesktopPane;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author vitor
 */
public class ViewMenu extends JFrame {

    /**
     * Creates new form Menu
     */
	private Connection conn;
    public ViewMenu(Connection conn) {
    	this.conn = conn;
        initComponents();
        //setExtendedState(JFrame.MAXIMIZED_BOTH);
        

        


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings({ "unchecked", "deprecation" })
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane2 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mMenu = new javax.swing.JMenu();
        mMenuProdutos = new javax.swing.JMenuItem();
        mMenuUsuario = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mMenuSair = new javax.swing.JMenuItem();
        mVendas = new javax.swing.JMenu();
        mFerramentas = new javax.swing.JMenu();
        mVendasVendas = new javax.swing.JMenuItem();
        miBackup = new javax.swing.JMenuItem();
        miRestore = new javax.swing.JMenuItem();
        mVendasRelatorioVendas = new javax.swing.JMenuItem();
        mAjuda = new javax.swing.JMenu();
        mAjudaAjuda = new javax.swing.JMenuItem();
        mAjudaSobre = new javax.swing.JMenuItem();

        /*setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setExtendedState(JFrame.MAXIMIZED_BOTH);
		setLocationRelativeTo(null);
		setBackground(null);
		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		setResizable(false);
        setContentPane(CreateContentPane());
        /*jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cerveja.png"))); // NOI18N
        jLabel1.setFocusable(false);
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setOpaque(true);
        jLabel1.setVerifyInputWhenFocusTarget(false);
        //jLabel1.setBounds(0, 0, 1050,  getContentPane().getHeight());
        jDesktopPane2.add(jLabel1);*/
		setJMenuBar(jMenuBar1);
		setTitle("Beer Shop");
		setExtendedState(Frame.MAXIMIZED_BOTH);
		setBackground(null);
		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		setUndecorated(true);
		setResizable(true);
		setMinimumSize(new Dimension(1080,800));

		setLocationRelativeTo(null);
		setContentPane(CreateContentPane());
		setIconImage(new javax.swing.ImageIcon(getClass().getResource("/Imagens/caneca-de-cervejax32.png")).getImage());


        getContentPane().add(jDesktopPane2);
   //     jDesktopPane2.setBounds(0, 0, getContentPane().getWidth(),  getContentPane().getHeight());


        mMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/MenuIcon.png"))); // NOI18N
        mMenu.setText("Menu");

        mMenuProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/produtos.png"))); // NOI18N
        mMenuProdutos.setText("Produtos");
        mMenuProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mMenuProdutosActionPerformed(evt);
            }
        });
        mMenu.add(mMenuProdutos);

        mMenuUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/assaltante.png"))); // NOI18N
        mMenuUsuario.setText("Usuário");
        mMenuUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mMenuUsuarioActionPerformed(evt);
            }
        });
        mMenu.add(mMenuUsuario);
        mMenu.add(jSeparator1);

        mMenuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/sair.png"))); // NOI18N
        mMenuSair.setText("Sair");
        mMenu.add(mMenuSair);
        mMenuSair.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
               System.exit(1);
            }
         });

        jMenuBar1.add(mMenu);

        mVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/vendaIcon.png"))); // NOI18N
        mVendas.setText("Vendas");

        mVendasVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/comercio.png"))); // NOI18N
        mVendasVendas.setText("Vendas");
        mVendasVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mVendasVendasActionPerformed(evt);
            }
        });
        mVendas.add(mVendasVendas);

        mVendasRelatorioVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/relatorio-de-venda.png"))); // NOI18N
        mVendasRelatorioVendas.setText("Relatório de Vendas");
        mVendasRelatorioVendas.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent e) {
				// TODO Auto-generated method stub
		        frameRelVendas frelvendas = new frameRelVendas(conn);
		        jDesktopPane2.add(frelvendas);
		        frelvendas.setPosicao();
		        frelvendas.show();
				
			}
		});
        mVendas.add(mVendasRelatorioVendas);

        jMenuBar1.add(mVendas);
        
        
        mFerramentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ferramentasx24.png"))); // NOI18N
        mFerramentas.setText("Ferramentas");

        miBackup.setText("Backup");
        miBackup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/copia-de-segurancax24.png"))); // NOI18N
        miBackup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miBackupActionPerformed(evt);
            }
        });
        mFerramentas.add(miBackup);

        miRestore.setText("Restore");
        miRestore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/restaurarx24.png"))); // NOI18N
        miRestore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miRestoreActionPerformed(evt);
            }
        });
        mFerramentas.add(miRestore);
        jMenuBar1.add(mFerramentas);


        mAjuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/computador-desktop.png"))); // NOI18N
        mAjuda.setText("Ajuda");

        mAjudaAjuda.setText("Ajuda");
        mAjuda.add(mAjudaAjuda);

        mAjudaSobre.setText("Sobre");
        mAjudaSobre.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent e) {
				// TODO Auto-generated method stub
		        frameSobre frameSobre = new frameSobre();
		        jDesktopPane2.add(frameSobre);
		        frameSobre.setPosicao();
		        frameSobre.show();
				
			}
		});
        mAjuda.add(mAjudaSobre);
        

        jMenuBar1.add(mAjuda);

        //setJMenuBar(jMenuBar1);
        setVisible(true);
        //pack();
        setLocationRelativeTo(null);
        
    }// </editor-fold>//GEN-END:initComponents

    private void mMenuProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mMenuProdutosActionPerformed
        // TODO add your handling code here:
        frameProdutos fprodutos = new frameProdutos(conn);
        jDesktopPane2.add(fprodutos);
        fprodutos.setPosicao();
        fprodutos.show();
    }//GEN-LAST:event_mMenuProdutosActionPerformed

    private void mMenuUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mMenuUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mMenuUsuarioActionPerformed

    private void mVendasVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mVendasVendasActionPerformed
        // TODO add your handling code here:
        FrameVendas fvendas = new FrameVendas(conn);
        jDesktopPane2.add(fvendas);
        fvendas.setPosicao();
        fvendas.show();
        
    }//GEN-LAST:event_mVendasVendasActionPerformed
    
	public Container CreateContentPane() {

		JPanel contentPane = new JPanel(new BorderLayout());
		try {
			jDesktopPane2 = new JDesktopPane() {
				Image im = ImageIO.read(new File(System.getProperty("user.dir") + "\\src\\Imagens\\wallpaper.jpg"));
				
				public void paintComponent(Graphics g) {
					g.drawImage(im, 0, 0, getWidth(), getHeight(), this);

				}
			};
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

		contentPane.setOpaque(true);
		contentPane.add(jDesktopPane2);
		return contentPane;
	}

    
    private void miRestoreActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    	frameRestore f = new frameRestore(conn);
    	jDesktopPane2.add(f);
    	f.setPosicao();
    	f.show();
    	
    }  
    
    private void miBackupActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    	
    	frameBackup f = new frameBackup(conn);
    	jDesktopPane2.add(f);
    	f.setPosicao();
    	f.show();
    }                                         



    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenu mAjuda;
    private javax.swing.JMenuItem mAjudaAjuda;
    private javax.swing.JMenuItem mAjudaSobre;
    private javax.swing.JMenu mMenu;
    private javax.swing.JMenuItem mMenuProdutos;
    private javax.swing.JMenuItem mMenuSair;
    private javax.swing.JMenu mFerramentas;
    private javax.swing.JMenuItem miBackup;
    private javax.swing.JMenuItem miRestore;
    private javax.swing.JMenuItem mMenuUsuario;
    private javax.swing.JMenu mVendas;
    private javax.swing.JMenuItem mVendasRelatorioVendas;
    private javax.swing.JMenuItem mVendasVendas;
    // End of variables declaration//GEN-END:variables
}
